# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0044_openapi_job_modify_req import V0044OpenapiJobModifyReq

class TestV0044OpenapiJobModifyReq(unittest.TestCase):
    """V0044OpenapiJobModifyReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044OpenapiJobModifyReq:
        """Test V0044OpenapiJobModifyReq
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044OpenapiJobModifyReq`
        """
        model = V0044OpenapiJobModifyReq()
        if include_optional:
            return V0044OpenapiJobModifyReq(
                job_id_list = [
                    ''
                    ],
                job_rec = slurmrestapi.models.v0/0/44_job_modify.v0.0.44_job_modify(
                    comment = slurmrestapi.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment(
                        administrator = '', 
                        job = '', 
                        system = '', ), 
                    derived_exit_code = slurmrestapi.models.v0/0/44_process_exit_code_verbose.v0.0.44_process_exit_code_verbose(
                        status = [
                            'INVALID'
                            ], 
                        return_code = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        signal = slurmrestapi.models.v0_0_44_process_exit_code_verbose_signal.v0_0_44_process_exit_code_verbose_signal(
                            id = slurmrestapi.models.v0/0/44_uint16_no_val_struct.v0.0.44_uint16_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            name = '', ), ), 
                    extra = '', 
                    tres = slurmrestapi.models.v0_0_44_job_modify_tres.v0_0_44_job_modify_tres(
                        allocated = [
                            slurmrestapi.models.v0/0/44_tres.v0.0.44_tres(
                                type = '', 
                                name = '', 
                                count = 56, )
                            ], ), 
                    wckey = '', ),
                meta = slurmrestapi.models.v0/0/44_openapi_meta.v0.0.44_openapi_meta(
                    plugin = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_plugin.slurm_v0041_get_shares_200_response_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_client.slurm_v0041_get_shares_200_response_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_slurm.slurm_v0041_get_shares_200_response_meta_slurm(
                        version = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_slurm_version.slurm_v0041_get_shares_200_response_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurmrestapi.models.v0/0/44_openapi_error.v0.0.44_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurmrestapi.models.v0/0/44_openapi_warning.v0.0.44_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0044OpenapiJobModifyReq(
        )
        """

    def testV0044OpenapiJobModifyReq(self):
        """Test V0044OpenapiJobModifyReq"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
