# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0040_qos_limits_min import V0040QosLimitsMin

class TestV0040QosLimitsMin(unittest.TestCase):
    """V0040QosLimitsMin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0040QosLimitsMin:
        """Test V0040QosLimitsMin
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0040QosLimitsMin`
        """
        model = V0040QosLimitsMin()
        if include_optional:
            return V0040QosLimitsMin(
                priority_threshold = slurmrestapi.models.v0/0/40_uint32_no_val.v0.0.40_uint32_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                tres = slurmrestapi.models.v0_0_40_qos_limits_min_tres.v0_0_40_qos_limits_min_tres(
                    per = slurmrestapi.models.v0_0_40_qos_limits_min_tres_per.v0_0_40_qos_limits_min_tres_per(
                        job = [
                            slurmrestapi.models.v0/0/40_tres.v0.0.40_tres(
                                type = '', 
                                name = '', 
                                id = 56, 
                                count = 56, )
                            ], ), )
            )
        else:
            return V0040QosLimitsMin(
        )
        """

    def testV0040QosLimitsMin(self):
        """Test V0040QosLimitsMin"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
