# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0042_openapi_meta import V0042OpenapiMeta

class TestV0042OpenapiMeta(unittest.TestCase):
    """V0042OpenapiMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042OpenapiMeta:
        """Test V0042OpenapiMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0042OpenapiMeta`
        """
        model = V0042OpenapiMeta()
        if include_optional:
            return V0042OpenapiMeta(
                plugin = slurmrestapi.models.v0_0_41_openapi_shares_resp_meta_plugin.v0_0_41_openapi_shares_resp_meta_plugin(
                    type = '', 
                    name = '', 
                    data_parser = '', 
                    accounting_storage = '', ),
                client = slurmrestapi.models.v0_0_41_openapi_shares_resp_meta_client.v0_0_41_openapi_shares_resp_meta_client(
                    source = '', 
                    user = '', 
                    group = '', ),
                command = [
                    ''
                    ],
                slurm = slurmrestapi.models.v0_0_41_openapi_shares_resp_meta_slurm.v0_0_41_openapi_shares_resp_meta_slurm(
                    version = slurmrestapi.models.v0_0_41_openapi_shares_resp_meta_slurm_version.v0_0_41_openapi_shares_resp_meta_slurm_version(
                        major = '', 
                        micro = '', 
                        minor = '', ), 
                    release = '', 
                    cluster = '', )
            )
        else:
            return V0042OpenapiMeta(
        )
        """

    def testV0042OpenapiMeta(self):
        """Test V0042OpenapiMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
