# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.slurm_v0041_get_shares200_response import SlurmV0041GetShares200Response

class TestSlurmV0041GetShares200Response(unittest.TestCase):
    """SlurmV0041GetShares200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlurmV0041GetShares200Response:
        """Test SlurmV0041GetShares200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlurmV0041GetShares200Response`
        """
        model = SlurmV0041GetShares200Response()
        if include_optional:
            return SlurmV0041GetShares200Response(
                shares = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares.slurm_v0041_get_shares_200_response_shares(
                    shares = [
                        slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner.slurm_v0041_get_shares_200_response_shares_shares_inner(
                            id = 56, 
                            cluster = '', 
                            name = '', 
                            parent = '', 
                            partition = '', 
                            shares_normalized = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_shares_normalized.slurm_v0041_get_shares_200_response_shares_shares_inner_shares_normalized(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            tres = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres.slurm_v0041_get_shares_200_response_shares_shares_inner_tres(
                                run_seconds = [
                                    slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner(
                                        name = '', 
                                        value = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner_value.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner_value(
                                            set = True, 
                                            infinite = True, 
                                            number = 56, ), )
                                    ], 
                                group_minutes = [
                                    slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner(
                                        name = '', )
                                    ], 
                                usage = [
                                    slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_usage_inner.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_usage_inner(
                                        name = '', )
                                    ], ), 
                            effective_usage = 1.337, 
                            usage_normalized = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_usage_normalized.slurm_v0041_get_shares_200_response_shares_shares_inner_usage_normalized(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            usage = 56, 
                            fairshare = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_fairshare.slurm_v0041_get_shares_200_response_shares_shares_inner_fairshare(
                                factor = 1.337, 
                                level = 1.337, ), 
                            type = [
                                'USER'
                                ], )
                        ], 
                    total_shares = 56, ),
                meta = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta.slurm_v0041_get_shares_200_response_meta(
                    plugin = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_plugin.slurm_v0041_get_shares_200_response_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_client.slurm_v0041_get_shares_200_response_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_slurm.slurm_v0041_get_shares_200_response_meta_slurm(
                        version = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_slurm_version.slurm_v0041_get_shares_200_response_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurmrestapi.models.slurm_v0041_get_shares_200_response_errors_inner.slurm_v0041_get_shares_200_response_errors_inner(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurmrestapi.models.slurm_v0041_get_shares_200_response_warnings_inner.slurm_v0041_get_shares_200_response_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return SlurmV0041GetShares200Response(
                shares = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares.slurm_v0041_get_shares_200_response_shares(
                    shares = [
                        slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner.slurm_v0041_get_shares_200_response_shares_shares_inner(
                            id = 56, 
                            cluster = '', 
                            name = '', 
                            parent = '', 
                            partition = '', 
                            shares_normalized = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_shares_normalized.slurm_v0041_get_shares_200_response_shares_shares_inner_shares_normalized(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            tres = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres.slurm_v0041_get_shares_200_response_shares_shares_inner_tres(
                                run_seconds = [
                                    slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner(
                                        name = '', 
                                        value = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner_value.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner_value(
                                            set = True, 
                                            infinite = True, 
                                            number = 56, ), )
                                    ], 
                                group_minutes = [
                                    slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_run_seconds_inner(
                                        name = '', )
                                    ], 
                                usage = [
                                    slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_usage_inner.slurm_v0041_get_shares_200_response_shares_shares_inner_tres_usage_inner(
                                        name = '', )
                                    ], ), 
                            effective_usage = 1.337, 
                            usage_normalized = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_usage_normalized.slurm_v0041_get_shares_200_response_shares_shares_inner_usage_normalized(
                                set = True, 
                                infinite = True, 
                                number = 1.337, ), 
                            usage = 56, 
                            fairshare = slurmrestapi.models.slurm_v0041_get_shares_200_response_shares_shares_inner_fairshare.slurm_v0041_get_shares_200_response_shares_shares_inner_fairshare(
                                factor = 1.337, 
                                level = 1.337, ), 
                            type = [
                                'USER'
                                ], )
                        ], 
                    total_shares = 56, ),
        )
        """

    def testSlurmV0041GetShares200Response(self):
        """Test SlurmV0041GetShares200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
