# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0041_openapi_diag_resp_statistics_pending_rpcs_by_hostlist_inner import V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner

class TestV0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner(unittest.TestCase):
    """V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner:
        """Test V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner`
        """
        model = V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner()
        if include_optional:
            return V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner(
                type_id = 56,
                message_type = '',
                count = [
                    ''
                    ]
            )
        else:
            return V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner(
                type_id = 56,
                message_type = '',
                count = [
                    ''
                    ],
        )
        """

    def testV0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner(self):
        """Test V0041OpenapiDiagRespStatisticsPendingRpcsByHostlistInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
