# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_assoc_max_per_account import V0043AssocMaxPerAccount

class TestV0043AssocMaxPerAccount(unittest.TestCase):
    """V0043AssocMaxPerAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043AssocMaxPerAccount:
        """Test V0043AssocMaxPerAccount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043AssocMaxPerAccount`
        """
        model = V0043AssocMaxPerAccount()
        if include_optional:
            return V0043AssocMaxPerAccount(
                wall_clock = slurmrestapi.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, )
            )
        else:
            return V0043AssocMaxPerAccount(
        )
        """

    def testV0043AssocMaxPerAccount(self):
        """Test V0043AssocMaxPerAccount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
