# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0044_job_het import V0044JobHet

class TestV0044JobHet(unittest.TestCase):
    """V0044JobHet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044JobHet:
        """Test V0044JobHet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044JobHet`
        """
        model = V0044JobHet()
        if include_optional:
            return V0044JobHet(
                job_id = 56,
                job_offset = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, )
            )
        else:
            return V0044JobHet(
        )
        """

    def testV0044JobHet(self):
        """Test V0044JobHet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
