# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_reservation_desc_msg import V0043ReservationDescMsg

class TestV0043ReservationDescMsg(unittest.TestCase):
    """V0043ReservationDescMsg unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043ReservationDescMsg:
        """Test V0043ReservationDescMsg
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043ReservationDescMsg`
        """
        model = V0043ReservationDescMsg()
        if include_optional:
            return V0043ReservationDescMsg(
                accounts = [
                    ''
                    ],
                burst_buffer = '',
                comment = '',
                core_count = slurmrestapi.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                duration = slurmrestapi.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                end_time = slurmrestapi.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                features = '',
                flags = [
                    'MAINT'
                    ],
                groups = [
                    ''
                    ],
                licenses = [
                    ''
                    ],
                max_start_delay = slurmrestapi.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                name = '',
                node_count = slurmrestapi.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                node_list = [
                    ''
                    ],
                partition = '',
                purge_completed = slurmrestapi.models.v0_0_43_reservation_info_purge_completed.v0_0_43_reservation_info_purge_completed(
                    time = slurmrestapi.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                start_time = slurmrestapi.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                tres = [
                    slurmrestapi.models.v0/0/43_tres.v0.0.43_tres(
                        type = '', 
                        name = '', 
                        id = 56, 
                        count = 56, )
                    ],
                users = [
                    ''
                    ]
            )
        else:
            return V0043ReservationDescMsg(
        )
        """

    def testV0043ReservationDescMsg(self):
        """Test V0043ReservationDescMsg"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
