# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0042_job_array_response_msg_entry import V0042JobArrayResponseMsgEntry

class TestV0042JobArrayResponseMsgEntry(unittest.TestCase):
    """V0042JobArrayResponseMsgEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042JobArrayResponseMsgEntry:
        """Test V0042JobArrayResponseMsgEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0042JobArrayResponseMsgEntry`
        """
        model = V0042JobArrayResponseMsgEntry()
        if include_optional:
            return V0042JobArrayResponseMsgEntry(
                job_id = 56,
                step_id = '',
                error = '',
                error_code = 56,
                why = ''
            )
        else:
            return V0042JobArrayResponseMsgEntry(
        )
        """

    def testV0042JobArrayResponseMsgEntry(self):
        """Test V0042JobArrayResponseMsgEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
