# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0041_openapi_shares_resp_meta_slurm import V0041OpenapiSharesRespMetaSlurm

class TestV0041OpenapiSharesRespMetaSlurm(unittest.TestCase):
    """V0041OpenapiSharesRespMetaSlurm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSharesRespMetaSlurm:
        """Test V0041OpenapiSharesRespMetaSlurm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSharesRespMetaSlurm`
        """
        model = V0041OpenapiSharesRespMetaSlurm()
        if include_optional:
            return V0041OpenapiSharesRespMetaSlurm(
                version = slurmrestapi.models.v0_0_41_openapi_shares_resp_meta_slurm_version.v0_0_41_openapi_shares_resp_meta_slurm_version(
                    major = '', 
                    micro = '', 
                    minor = '', ),
                release = '',
                cluster = ''
            )
        else:
            return V0041OpenapiSharesRespMetaSlurm(
        )
        """

    def testV0041OpenapiSharesRespMetaSlurm(self):
        """Test V0041OpenapiSharesRespMetaSlurm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
