# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0041_openapi_job_info_resp_jobs_inner_pre_sus_time import V0041OpenapiJobInfoRespJobsInnerPreSusTime

class TestV0041OpenapiJobInfoRespJobsInnerPreSusTime(unittest.TestCase):
    """V0041OpenapiJobInfoRespJobsInnerPreSusTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiJobInfoRespJobsInnerPreSusTime:
        """Test V0041OpenapiJobInfoRespJobsInnerPreSusTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiJobInfoRespJobsInnerPreSusTime`
        """
        model = V0041OpenapiJobInfoRespJobsInnerPreSusTime()
        if include_optional:
            return V0041OpenapiJobInfoRespJobsInnerPreSusTime(
                set = True,
                infinite = True,
                number = 56
            )
        else:
            return V0041OpenapiJobInfoRespJobsInnerPreSusTime(
        )
        """

    def testV0041OpenapiJobInfoRespJobsInnerPreSusTime(self):
        """Test V0041OpenapiJobInfoRespJobsInnerPreSusTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
