# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0040_schedule_exit_fields import V0040ScheduleExitFields

class TestV0040ScheduleExitFields(unittest.TestCase):
    """V0040ScheduleExitFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0040ScheduleExitFields:
        """Test V0040ScheduleExitFields
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0040ScheduleExitFields`
        """
        model = V0040ScheduleExitFields()
        if include_optional:
            return V0040ScheduleExitFields(
                end_job_queue = 56,
                default_queue_depth = 56,
                max_job_start = 56,
                max_rpc_cnt = 56,
                max_sched_time = 56,
                licenses = 56
            )
        else:
            return V0040ScheduleExitFields(
        )
        """

    def testV0040ScheduleExitFields(self):
        """Test V0040ScheduleExitFields"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
