# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_assoc_max_tres_minutes import V0043AssocMaxTresMinutes

class TestV0043AssocMaxTresMinutes(unittest.TestCase):
    """V0043AssocMaxTresMinutes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043AssocMaxTresMinutes:
        """Test V0043AssocMaxTresMinutes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043AssocMaxTresMinutes`
        """
        model = V0043AssocMaxTresMinutes()
        if include_optional:
            return V0043AssocMaxTresMinutes(
                total = [
                    slurmrestapi.models.v0/0/43_tres.v0.0.43_tres(
                        type = '', 
                        name = '', 
                        id = 56, 
                        count = 56, )
                    ],
                per = slurmrestapi.models.v0_0_43_qos_limits_min_tres_per.v0_0_43_qos_limits_min_tres_per(
                    job = [
                        slurmrestapi.models.v0/0/43_tres.v0.0.43_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], )
            )
        else:
            return V0043AssocMaxTresMinutes(
        )
        """

    def testV0043AssocMaxTresMinutes(self):
        """Test V0043AssocMaxTresMinutes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
