# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0039_assoc_usage import V0039AssocUsage

class TestV0039AssocUsage(unittest.TestCase):
    """V0039AssocUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0039AssocUsage:
        """Test V0039AssocUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0039AssocUsage`
        """
        model = V0039AssocUsage()
        if include_optional:
            return V0039AssocUsage(
                accrue_job_count = 56,
                group_used_wallclock = 1.337,
                fairshare_factor = 1.337,
                fairshare_shares = 56,
                normalized_priority = 1.337,
                normalized_shares = 1.337,
                effective_normalized_usage = 1.337,
                normalized_usage = 1.337,
                raw_usage = 1.337,
                active_jobs = 56,
                job_count = 56,
                fairshare_level = 1.337
            )
        else:
            return V0039AssocUsage(
        )
        """

    def testV0039AssocUsage(self):
        """Test V0039AssocUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
