# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_stats_msg_rpc_type import V0043StatsMsgRpcType

class TestV0043StatsMsgRpcType(unittest.TestCase):
    """V0043StatsMsgRpcType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043StatsMsgRpcType:
        """Test V0043StatsMsgRpcType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043StatsMsgRpcType`
        """
        model = V0043StatsMsgRpcType()
        if include_optional:
            return V0043StatsMsgRpcType(
                type_id = 56,
                message_type = '',
                count = 56,
                queued = 56,
                dropped = 56,
                cycle_last = 56,
                cycle_max = 56,
                total_time = 56,
                average_time = slurmrestapi.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, )
            )
        else:
            return V0043StatsMsgRpcType(
                type_id = 56,
                message_type = '',
                count = 56,
                queued = 56,
                dropped = 56,
                cycle_last = 56,
                cycle_max = 56,
                total_time = 56,
                average_time = slurmrestapi.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
        )
        """

    def testV0043StatsMsgRpcType(self):
        """Test V0043StatsMsgRpcType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
