# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_mcs import V0041OpenapiSlurmdbdJobsRespJobsInnerMcs

class TestV0041OpenapiSlurmdbdJobsRespJobsInnerMcs(unittest.TestCase):
    """V0041OpenapiSlurmdbdJobsRespJobsInnerMcs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdJobsRespJobsInnerMcs:
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerMcs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdJobsRespJobsInnerMcs`
        """
        model = V0041OpenapiSlurmdbdJobsRespJobsInnerMcs()
        if include_optional:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerMcs(
                label = ''
            )
        else:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerMcs(
        )
        """

    def testV0041OpenapiSlurmdbdJobsRespJobsInnerMcs(self):
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerMcs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
