# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0044_assoc import V0044Assoc

class TestV0044Assoc(unittest.TestCase):
    """V0044Assoc unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044Assoc:
        """Test V0044Assoc
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044Assoc`
        """
        model = V0044Assoc()
        if include_optional:
            return V0044Assoc(
                accounting = [
                    slurmrestapi.models.v0/0/44_accounting.v0.0.44_accounting(
                        allocated = slurmrestapi.models.v0_0_44_accounting_allocated.v0_0_44_accounting_allocated(
                            seconds = 56, ), 
                        id = 56, 
                        id_alt = 56, 
                        start = 56, 
                        tres = slurmrestapi.models.v0/0/44_tres.v0.0.44_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, ), )
                    ],
                account = '',
                cluster = '',
                comment = '',
                default = slurmrestapi.models.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_default.v0_0_41_openapi_slurmdbd_config_resp_associations_inner_default(
                    qos = '', ),
                flags = [
                    'DELETED'
                    ],
                max = slurmrestapi.models.v0_0_44_assoc_max.v0_0_44_assoc_max(
                    jobs = slurmrestapi.models.v0_0_44_assoc_max_jobs.v0_0_44_assoc_max_jobs(
                        per = slurmrestapi.models.v0_0_44_assoc_max_jobs_per.v0_0_44_assoc_max_jobs_per(
                            count = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            accruing = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                                set = True, 
                                infinite = True, 
                                number = 56, ), 
                            submitted = , 
                            wall_clock = , ), 
                        active = , 
                        accruing = , 
                        total = , ), 
                    tres = slurmrestapi.models.v0_0_44_assoc_max_tres.v0_0_44_assoc_max_tres(
                        group = slurmrestapi.models.v0_0_44_assoc_max_tres_group.v0_0_44_assoc_max_tres_group(
                            minutes = [
                                slurmrestapi.models.v0/0/44_tres.v0.0.44_tres(
                                    type = '', 
                                    name = '', 
                                    id = 56, )
                                ], ), 
                        minutes = slurmrestapi.models.v0_0_44_assoc_max_tres_minutes.v0_0_44_assoc_max_tres_minutes(), ), 
                    per = slurmrestapi.models.v0_0_44_assoc_max_per.v0_0_44_assoc_max_per(
                        account = slurmrestapi.models.v0_0_44_assoc_max_per_account.v0_0_44_assoc_max_per_account(), ), ),
                id = 56,
                is_default = True,
                lineage = '',
                min = slurmrestapi.models.v0_0_44_assoc_min.v0_0_44_assoc_min(
                    priority_threshold = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), ),
                parent_account = '',
                partition = '',
                priority = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                qos = [
                    ''
                    ],
                shares_raw = 56,
                user = ''
            )
        else:
            return V0044Assoc(
                user = '',
        )
        """

    def testV0044Assoc(self):
        """Test V0044Assoc"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
