# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0044_cluster_rec import V0044ClusterRec

class TestV0044ClusterRec(unittest.TestCase):
    """V0044ClusterRec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044ClusterRec:
        """Test V0044ClusterRec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044ClusterRec`
        """
        model = V0044ClusterRec()
        if include_optional:
            return V0044ClusterRec(
                controller = slurmrestapi.models.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_controller.v0_0_41_openapi_slurmdbd_config_resp_clusters_inner_controller(
                    host = '', 
                    port = 56, ),
                flags = [
                    'DELETED'
                    ],
                name = '',
                nodes = '',
                select_plugin = '',
                associations = slurmrestapi.models.v0_0_44_cluster_rec_associations.v0_0_44_cluster_rec_associations(
                    root = slurmrestapi.models.v0/0/44_assoc_short.v0.0.44_assoc_short(
                        account = '', 
                        cluster = '', 
                        partition = '', 
                        user = '', 
                        id = 56, ), ),
                rpc_version = 56,
                tres = [
                    slurmrestapi.models.v0/0/44_tres.v0.0.44_tres(
                        type = '', 
                        name = '', 
                        id = 56, 
                        count = 56, )
                    ]
            )
        else:
            return V0044ClusterRec(
        )
        """

    def testV0044ClusterRec(self):
        """Test V0044ClusterRec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
