# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0042_rollup_stats import V0042RollupStats

class TestV0042RollupStats(unittest.TestCase):
    """V0042RollupStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042RollupStats:
        """Test V0042RollupStats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0042RollupStats`
        """
        model = V0042RollupStats()
        if include_optional:
            return V0042RollupStats(
                hourly = slurmrestapi.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly(
                    count = 56, 
                    last_run = 56, 
                    duration = slurmrestapi.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_hourly_duration(
                        last = 56, 
                        max = 56, 
                        time = 56, ), ),
                daily = slurmrestapi.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily(
                    count = 56, 
                    last_run = 56, 
                    duration = slurmrestapi.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily_duration.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_daily_duration(
                        last = 56, 
                        max = 56, 
                        time = 56, ), ),
                monthly = slurmrestapi.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_monthly.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_monthly(
                    count = 56, 
                    last_run = 56, 
                    duration = slurmrestapi.models.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_monthly_duration.v0_0_41_openapi_slurmdbd_stats_resp_statistics_rollups_monthly_duration(
                        last = 56, 
                        max = 56, 
                        time = 56, ), )
            )
        else:
            return V0042RollupStats(
        )
        """

    def testV0042RollupStats(self):
        """Test V0042RollupStats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
