# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_wckey import V0043Wckey

class TestV0043Wckey(unittest.TestCase):
    """V0043Wckey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043Wckey:
        """Test V0043Wckey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043Wckey`
        """
        model = V0043Wckey()
        if include_optional:
            return V0043Wckey(
                accounting = [
                    slurmrestapi.models.v0/0/43_accounting.v0.0.43_accounting(
                        allocated = slurmrestapi.models.v0_0_44_accounting_allocated.v0_0_44_accounting_allocated(
                            seconds = 56, ), 
                        id = 56, 
                        id_alt = 56, 
                        start = 56, 
                        tres = slurmrestapi.models.v0/0/43_tres.v0.0.43_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, ), )
                    ],
                cluster = '',
                id = 56,
                name = '',
                user = '',
                flags = [
                    'DELETED'
                    ]
            )
        else:
            return V0043Wckey(
                cluster = '',
                name = '',
                user = '',
        )
        """

    def testV0043Wckey(self):
        """Test V0043Wckey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
