# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_step_statistics import V0043StepStatistics

class TestV0043StepStatistics(unittest.TestCase):
    """V0043StepStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043StepStatistics:
        """Test V0043StepStatistics
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043StepStatistics`
        """
        model = V0043StepStatistics()
        if include_optional:
            return V0043StepStatistics(
                cpu = slurmrestapi.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_cpu.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_statistics_CPU(
                    actual_frequency = 56, ),
                energy = slurmrestapi.models.v0_0_43_step_statistics_energy.v0_0_43_step_statistics_energy(
                    consumed = slurmrestapi.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), )
            )
        else:
            return V0043StepStatistics(
        )
        """

    def testV0043StepStatistics(self):
        """Test V0043StepStatistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
