# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0039_reservations_response import V0039ReservationsResponse

class TestV0039ReservationsResponse(unittest.TestCase):
    """V0039ReservationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0039ReservationsResponse:
        """Test V0039ReservationsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0039ReservationsResponse`
        """
        model = V0039ReservationsResponse()
        if include_optional:
            return V0039ReservationsResponse(
                meta = slurmrestapi.models.v0/0/39_meta.v0.0.39_meta(
                    plugin = slurmrestapi.models.dbv0_0_39_meta_plugin.dbv0_0_39_meta_plugin(
                        type = '', 
                        name = '', ), 
                    slurm = slurmrestapi.models.dbv0_0_39_meta_slurm.dbv0_0_39_meta_Slurm(
                        version = slurmrestapi.models.dbv0_0_39_meta_slurm_version.dbv0_0_39_meta_Slurm_version(
                            major = 56, 
                            micro = 56, 
                            minor = 56, ), 
                        release = '', ), ),
                errors = [
                    slurmrestapi.models.v0/0/39_error.v0.0.39_error(
                        error_number = 56, 
                        error = '', 
                        source = '', 
                        description = '', )
                    ],
                warnings = [
                    slurmrestapi.models.v0/0/39_warning.v0.0.39_warning(
                        warning = '', 
                        source = '', 
                        description = '', )
                    ],
                reservations = [
                    slurmrestapi.models.v0/0/39_reservation_info.v0.0.39_reservation_info(
                        accounts = '', 
                        burst_buffer = '', 
                        core_count = 56, 
                        core_specializations = [
                            slurmrestapi.models.v0/0/39_reservation_core_spec.v0.0.39_reservation_core_spec(
                                node = '', 
                                core = '', )
                            ], 
                        end_time = 56, 
                        features = '', 
                        flags = [
                            'MAINT'
                            ], 
                        groups = '', 
                        licenses = '', 
                        max_start_delay = 56, 
                        name = '', 
                        node_count = 56, 
                        node_list = '', 
                        partition = '', 
                        purge_completed = slurmrestapi.models.v0_0_39_reservation_info_purge_completed.v0_0_39_reservation_info_purge_completed(
                            time = slurmrestapi.models.v0/0/39_uint32_no_val.v0.0.39_uint32_no_val(
                                set = True, 
                                infinite = True, 
                                number = 56, ), ), 
                        start_time = 56, 
                        watts = slurmrestapi.models.v0/0/39_uint32_no_val.v0.0.39_uint32_no_val(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        tres = '', 
                        users = '', )
                    ]
            )
        else:
            return V0039ReservationsResponse(
        )
        """

    def testV0039ReservationsResponse(self):
        """Test V0039ReservationsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
