# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0040_account import V0040Account

class TestV0040Account(unittest.TestCase):
    """V0040Account unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0040Account:
        """Test V0040Account
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0040Account`
        """
        model = V0040Account()
        if include_optional:
            return V0040Account(
                associations = [
                    slurmrestapi.models.v0/0/40_assoc_short.v0.0.40_assoc_short(
                        account = '', 
                        cluster = '', 
                        partition = '', 
                        user = '', 
                        id = 56, )
                    ],
                coordinators = [
                    slurmrestapi.models.v0/0/40_coord.v0.0.40_coord(
                        name = '', 
                        direct = True, )
                    ],
                description = '',
                name = '',
                organization = '',
                flags = [
                    'DELETED'
                    ]
            )
        else:
            return V0040Account(
                description = '',
                name = '',
                organization = '',
        )
        """

    def testV0040Account(self):
        """Test V0040Account"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
