# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0044_job_modify import V0044JobModify

class TestV0044JobModify(unittest.TestCase):
    """V0044JobModify unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044JobModify:
        """Test V0044JobModify
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044JobModify`
        """
        model = V0044JobModify()
        if include_optional:
            return V0044JobModify(
                comment = slurmrestapi.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_comment(
                    administrator = '', 
                    job = '', 
                    system = '', ),
                derived_exit_code = slurmrestapi.models.v0/0/44_process_exit_code_verbose.v0.0.44_process_exit_code_verbose(
                    status = [
                        'INVALID'
                        ], 
                    return_code = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    signal = slurmrestapi.models.v0_0_44_process_exit_code_verbose_signal.v0_0_44_process_exit_code_verbose_signal(
                        id = slurmrestapi.models.v0/0/44_uint16_no_val_struct.v0.0.44_uint16_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        name = '', ), ),
                extra = '',
                tres = slurmrestapi.models.v0_0_44_job_modify_tres.v0_0_44_job_modify_tres(
                    allocated = [
                        slurmrestapi.models.v0/0/44_tres.v0.0.44_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], ),
                wckey = ''
            )
        else:
            return V0044JobModify(
        )
        """

    def testV0044JobModify(self):
        """Test V0044JobModify"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
