# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_job_res_core import V0043JobResCore

class TestV0043JobResCore(unittest.TestCase):
    """V0043JobResCore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043JobResCore:
        """Test V0043JobResCore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043JobResCore`
        """
        model = V0043JobResCore()
        if include_optional:
            return V0043JobResCore(
                index = 56,
                status = [
                    'INVALID'
                    ]
            )
        else:
            return V0043JobResCore(
                index = 56,
                status = [
                    'INVALID'
                    ],
        )
        """

    def testV0043JobResCore(self):
        """Test V0043JobResCore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
