# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_time import V0041OpenapiSlurmdbdJobsRespJobsInnerTime

class TestV0041OpenapiSlurmdbdJobsRespJobsInnerTime(unittest.TestCase):
    """V0041OpenapiSlurmdbdJobsRespJobsInnerTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdJobsRespJobsInnerTime:
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdJobsRespJobsInnerTime`
        """
        model = V0041OpenapiSlurmdbdJobsRespJobsInnerTime()
        if include_optional:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerTime(
                elapsed = 56,
                eligible = 56,
                end = 56,
                planned = slurmrestapi.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_time_planned(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                start = 56,
                submission = 56,
                suspended = 56,
                system = slurmrestapi.models.v0_0_40_job_time_system.v0_0_40_job_time_system(
                    seconds = 56, 
                    microseconds = 56, ),
                limit = slurmrestapi.models.v0_0_41_job_desc_msg_time_limit.v0_0_41_job_desc_msg_time_limit(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                total = slurmrestapi.models.v0_0_40_job_time_total.v0_0_40_job_time_total(
                    seconds = 56, 
                    microseconds = 56, ),
                user = slurmrestapi.models.v0_0_40_job_time_user.v0_0_40_job_time_user(
                    seconds = 56, 
                    microseconds = 56, )
            )
        else:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerTime(
        )
        """

    def testV0041OpenapiSlurmdbdJobsRespJobsInnerTime(self):
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
