# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.slurm_v0041_get_shares200_response_errors_inner import SlurmV0041GetShares200ResponseErrorsInner

class TestSlurmV0041GetShares200ResponseErrorsInner(unittest.TestCase):
    """SlurmV0041GetShares200ResponseErrorsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlurmV0041GetShares200ResponseErrorsInner:
        """Test SlurmV0041GetShares200ResponseErrorsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlurmV0041GetShares200ResponseErrorsInner`
        """
        model = SlurmV0041GetShares200ResponseErrorsInner()
        if include_optional:
            return SlurmV0041GetShares200ResponseErrorsInner(
                description = '',
                error_number = 56,
                error = '',
                source = ''
            )
        else:
            return SlurmV0041GetShares200ResponseErrorsInner(
        )
        """

    def testSlurmV0041GetShares200ResponseErrorsInner(self):
        """Test SlurmV0041GetShares200ResponseErrorsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
