# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0042_uint16_no_val_struct import V0042Uint16NoValStruct

class TestV0042Uint16NoValStruct(unittest.TestCase):
    """V0042Uint16NoValStruct unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0042Uint16NoValStruct:
        """Test V0042Uint16NoValStruct
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0042Uint16NoValStruct`
        """
        model = V0042Uint16NoValStruct()
        if include_optional:
            return V0042Uint16NoValStruct(
                set = True,
                infinite = True,
                number = 56
            )
        else:
            return V0042Uint16NoValStruct(
        )
        """

    def testV0042Uint16NoValStruct(self):
        """Test V0042Uint16NoValStruct"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
