# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0044_openapi_kill_jobs_resp import V0044OpenapiKillJobsResp

class TestV0044OpenapiKillJobsResp(unittest.TestCase):
    """V0044OpenapiKillJobsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044OpenapiKillJobsResp:
        """Test V0044OpenapiKillJobsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044OpenapiKillJobsResp`
        """
        model = V0044OpenapiKillJobsResp()
        if include_optional:
            return V0044OpenapiKillJobsResp(
                status = [
                    slurmrestapi.models.v0/0/44_kill_jobs_resp_job.v0.0.44_kill_jobs_resp_job(
                        error = slurmrestapi.models.v0_0_41_openapi_kill_jobs_resp_status_inner_error.v0_0_41_openapi_kill_jobs_resp_status_inner_error(
                            string = '', 
                            code = 56, 
                            message = '', ), 
                        step_id = '', 
                        job_id = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        federation = slurmrestapi.models.v0_0_41_openapi_kill_jobs_resp_status_inner_federation.v0_0_41_openapi_kill_jobs_resp_status_inner_federation(
                            sibling = '', ), )
                    ],
                meta = slurmrestapi.models.v0/0/44_openapi_meta.v0.0.44_openapi_meta(
                    plugin = slurmrestapi.models.v0_0_41_openapi_shares_resp_meta_plugin.v0_0_41_openapi_shares_resp_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurmrestapi.models.v0_0_41_openapi_shares_resp_meta_client.v0_0_41_openapi_shares_resp_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurmrestapi.models.v0_0_41_openapi_shares_resp_meta_slurm.v0_0_41_openapi_shares_resp_meta_slurm(
                        version = slurmrestapi.models.v0_0_41_openapi_shares_resp_meta_slurm_version.v0_0_41_openapi_shares_resp_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurmrestapi.models.v0/0/44_openapi_error.v0.0.44_openapi_error(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurmrestapi.models.v0/0/44_openapi_warning.v0.0.44_openapi_warning(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0044OpenapiKillJobsResp(
                status = [
                    slurmrestapi.models.v0/0/44_kill_jobs_resp_job.v0.0.44_kill_jobs_resp_job(
                        error = slurmrestapi.models.v0_0_41_openapi_kill_jobs_resp_status_inner_error.v0_0_41_openapi_kill_jobs_resp_status_inner_error(
                            string = '', 
                            code = 56, 
                            message = '', ), 
                        step_id = '', 
                        job_id = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                            set = True, 
                            infinite = True, 
                            number = 56, ), 
                        federation = slurmrestapi.models.v0_0_41_openapi_kill_jobs_resp_status_inner_federation.v0_0_41_openapi_kill_jobs_resp_status_inner_federation(
                            sibling = '', ), )
                    ],
        )
        """

    def testV0044OpenapiKillJobsResp(self):
        """Test V0044OpenapiKillJobsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
