# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0041_openapi_accounts_resp import V0041OpenapiAccountsResp

class TestV0041OpenapiAccountsResp(unittest.TestCase):
    """V0041OpenapiAccountsResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiAccountsResp:
        """Test V0041OpenapiAccountsResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiAccountsResp`
        """
        model = V0041OpenapiAccountsResp()
        if include_optional:
            return V0041OpenapiAccountsResp(
                accounts = [
                    slurmrestapi.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner(
                        associations = [
                            slurmrestapi.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', 
                                id = 56, )
                            ], 
                        coordinators = [
                            slurmrestapi.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_coordinators_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_coordinators_inner(
                                name = '', 
                                direct = True, )
                            ], 
                        description = '', 
                        name = '', 
                        organization = '', 
                        flags = [
                            'DELETED'
                            ], )
                    ],
                meta = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta.slurm_v0041_get_shares_200_response_meta(
                    plugin = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_plugin.slurm_v0041_get_shares_200_response_meta_plugin(
                        type = '', 
                        name = '', 
                        data_parser = '', 
                        accounting_storage = '', ), 
                    client = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_client.slurm_v0041_get_shares_200_response_meta_client(
                        source = '', 
                        user = '', 
                        group = '', ), 
                    command = [
                        ''
                        ], 
                    slurm = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_slurm.slurm_v0041_get_shares_200_response_meta_slurm(
                        version = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_slurm_version.slurm_v0041_get_shares_200_response_meta_slurm_version(
                            major = '', 
                            micro = '', 
                            minor = '', ), 
                        release = '', 
                        cluster = '', ), ),
                errors = [
                    slurmrestapi.models.slurm_v0041_get_shares_200_response_errors_inner.slurm_v0041_get_shares_200_response_errors_inner(
                        description = '', 
                        error_number = 56, 
                        error = '', 
                        source = '', )
                    ],
                warnings = [
                    slurmrestapi.models.slurm_v0041_get_shares_200_response_warnings_inner.slurm_v0041_get_shares_200_response_warnings_inner(
                        description = '', 
                        source = '', )
                    ]
            )
        else:
            return V0041OpenapiAccountsResp(
                accounts = [
                    slurmrestapi.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner(
                        associations = [
                            slurmrestapi.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_associations_inner(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', 
                                id = 56, )
                            ], 
                        coordinators = [
                            slurmrestapi.models.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_coordinators_inner.v0_0_41_openapi_slurmdbd_config_resp_accounts_inner_coordinators_inner(
                                name = '', 
                                direct = True, )
                            ], 
                        description = '', 
                        name = '', 
                        organization = '', 
                        flags = [
                            'DELETED'
                            ], )
                    ],
        )
        """

    def testV0041OpenapiAccountsResp(self):
        """Test V0041OpenapiAccountsResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
