# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.slurm_v0041_get_diag200_response_statistics_req_time import SlurmV0041GetDiag200ResponseStatisticsReqTime

class TestSlurmV0041GetDiag200ResponseStatisticsReqTime(unittest.TestCase):
    """SlurmV0041GetDiag200ResponseStatisticsReqTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlurmV0041GetDiag200ResponseStatisticsReqTime:
        """Test SlurmV0041GetDiag200ResponseStatisticsReqTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlurmV0041GetDiag200ResponseStatisticsReqTime`
        """
        model = SlurmV0041GetDiag200ResponseStatisticsReqTime()
        if include_optional:
            return SlurmV0041GetDiag200ResponseStatisticsReqTime(
                set = True,
                infinite = True,
                number = 56
            )
        else:
            return SlurmV0041GetDiag200ResponseStatisticsReqTime(
        )
        """

    def testSlurmV0041GetDiag200ResponseStatisticsReqTime(self):
        """Test SlurmV0041GetDiag200ResponseStatisticsReqTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
