# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0041_openapi_job_info_resp_jobs_inner_derived_exit_code_signal import V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal

class TestV0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal(unittest.TestCase):
    """V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal:
        """Test V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal`
        """
        model = V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal()
        if include_optional:
            return V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal(
                id = slurmrestapi.models.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id.v0_0_41_openapi_job_info_resp_jobs_inner_derived_exit_code_signal_id(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                name = ''
            )
        else:
            return V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal(
        )
        """

    def testV0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal(self):
        """Test V0041OpenapiJobInfoRespJobsInnerDerivedExitCodeSignal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
