# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0039_assoc_max_per import V0039AssocMaxPer

class TestV0039AssocMaxPer(unittest.TestCase):
    """V0039AssocMaxPer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0039AssocMaxPer:
        """Test V0039AssocMaxPer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0039AssocMaxPer`
        """
        model = V0039AssocMaxPer()
        if include_optional:
            return V0039AssocMaxPer(
                account = slurmrestapi.models.v0_0_39_assoc_max_per_account.v0_0_39_assoc_max_per_account(
                    wall_clock = slurmrestapi.models.v0/0/39_uint32_no_val.v0.0.39_uint32_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), )
            )
        else:
            return V0039AssocMaxPer(
        )
        """

    def testV0039AssocMaxPer(self):
        """Test V0039AssocMaxPer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
