# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_users_add_cond import V0043UsersAddCond

class TestV0043UsersAddCond(unittest.TestCase):
    """V0043UsersAddCond unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043UsersAddCond:
        """Test V0043UsersAddCond
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043UsersAddCond`
        """
        model = V0043UsersAddCond()
        if include_optional:
            return V0043UsersAddCond(
                accounts = [
                    ''
                    ],
                association = slurmrestapi.models.v0/0/43_assoc_rec_set.v0.0.43_assoc_rec_set(
                    comment = '', 
                    defaultqos = '', 
                    grpjobs = slurmrestapi.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    grpjobsaccrue = slurmrestapi.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    grpsubmitjobs = , 
                    grptres = [
                        slurmrestapi.models.v0/0/43_tres.v0.0.43_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    grptresmins = [
                        slurmrestapi.models.v0/0/43_tres.v0.0.43_tres(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    grptresrunmins = , 
                    grpwall = , 
                    maxjobs = , 
                    maxjobsaccrue = , 
                    maxsubmitjobs = , 
                    maxtresminsperjob = , 
                    maxtresrunmins = , 
                    maxtresperjob = , 
                    maxtrespernode = , 
                    maxwalldurationperjob = , 
                    minpriothresh = , 
                    parent = '', 
                    priority = , 
                    qoslevel = [
                        ''
                        ], 
                    fairshare = 56, ),
                clusters = [
                    ''
                    ],
                partitions = [
                    ''
                    ],
                users = [
                    ''
                    ],
                wckeys = [
                    ''
                    ]
            )
        else:
            return V0043UsersAddCond(
                users = [
                    ''
                    ],
        )
        """

    def testV0043UsersAddCond(self):
        """Test V0043UsersAddCond"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
