# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0041_openapi_slurmdbd_jobs_resp_jobs_inner_time_total import V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal

class TestV0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal(unittest.TestCase):
    """V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal:
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal`
        """
        model = V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal()
        if include_optional:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal(
                seconds = 56,
                microseconds = 56
            )
        else:
            return V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal(
        )
        """

    def testV0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal(self):
        """Test V0041OpenapiSlurmdbdJobsRespJobsInnerTimeTotal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
