# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0044_cluster_rec_associations import V0044ClusterRecAssociations

class TestV0044ClusterRecAssociations(unittest.TestCase):
    """V0044ClusterRecAssociations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044ClusterRecAssociations:
        """Test V0044ClusterRecAssociations
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044ClusterRecAssociations`
        """
        model = V0044ClusterRecAssociations()
        if include_optional:
            return V0044ClusterRecAssociations(
                root = slurmrestapi.models.v0/0/44_assoc_short.v0.0.44_assoc_short(
                    account = '', 
                    cluster = '', 
                    partition = '', 
                    user = '', 
                    id = 56, )
            )
        else:
            return V0044ClusterRecAssociations(
        )
        """

    def testV0044ClusterRecAssociations(self):
        """Test V0044ClusterRecAssociations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
