# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0039_node import V0039Node

class TestV0039Node(unittest.TestCase):
    """V0039Node unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0039Node:
        """Test V0039Node
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0039Node`
        """
        model = V0039Node()
        if include_optional:
            return V0039Node(
                architecture = '',
                burstbuffer_network_address = '',
                boards = 56,
                boot_time = 56,
                cluster_name = '',
                cores = 56,
                specialized_cores = 56,
                cpu_binding = 56,
                cpu_load = slurmrestapi.models.v0/0/39_uint32_no_val.v0.0.39_uint32_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                free_mem = slurmrestapi.models.v0/0/39_uint64_no_val.v0.0.39_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                cpus = 56,
                effective_cpus = 56,
                specialized_cpus = '',
                energy = slurmrestapi.models.v0/0/39_acct_gather_energy.v0.0.39_acct_gather_energy(
                    average_watts = 56, 
                    base_consumed_energy = 56, 
                    consumed_energy = 56, 
                    current_watts = slurmrestapi.models.v0/0/39_uint32_no_val.v0.0.39_uint32_no_val(
                        set = True, 
                        infinite = True, 
                        number = 56, ), 
                    previous_consumed_energy = 56, 
                    last_collected = 56, ),
                external_sensors = slurmrestapi.models.v0/0/39_ext_sensors_data.v0.0.39_ext_sensors_data(),
                extra = '',
                power = slurmrestapi.models.v0/0/39_power_mgmt_data.v0.0.39_power_mgmt_data(),
                features = [
                    ''
                    ],
                active_features = [
                    ''
                    ],
                gres = '',
                gres_drained = '',
                gres_used = '',
                last_busy = 56,
                mcs_label = '',
                specialized_memory = 56,
                name = '',
                next_state_after_reboot = [
                    'INVALID'
                    ],
                address = '',
                hostname = '',
                state = [
                    'INVALID'
                    ],
                operating_system = '',
                owner = '',
                partitions = [
                    ''
                    ],
                port = 56,
                real_memory = 56,
                comment = '',
                reason = '',
                reason_changed_at = 56,
                reason_set_by_user = '',
                resume_after = slurmrestapi.models.v0/0/39_uint64_no_val.v0.0.39_uint64_no_val(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                reservation = '',
                alloc_memory = 56,
                alloc_cpus = 56,
                alloc_idle_cpus = 56,
                tres_used = '',
                tres_weighted = 1.337,
                slurmd_start_time = 56,
                sockets = 56,
                threads = 56,
                temporary_disk = 56,
                weight = 56,
                tres = '',
                version = ''
            )
        else:
            return V0039Node(
        )
        """

    def testV0039Node(self):
        """Test V0039Node"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
