# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_step_time import V0043StepTime

class TestV0043StepTime(unittest.TestCase):
    """V0043StepTime unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043StepTime:
        """Test V0043StepTime
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043StepTime`
        """
        model = V0043StepTime()
        if include_optional:
            return V0043StepTime(
                elapsed = 56,
                end = slurmrestapi.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                start = slurmrestapi.models.v0/0/43_uint64_no_val_struct.v0.0.43_uint64_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                suspended = 56,
                system = slurmrestapi.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_system(
                    seconds = 56, 
                    microseconds = 56, ),
                limit = slurmrestapi.models.v0/0/43_uint32_no_val_struct.v0.0.43_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                total = slurmrestapi.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_total.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_total(
                    seconds = 56, 
                    microseconds = 56, ),
                user = slurmrestapi.models.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_user.v0_0_41_openapi_slurmdbd_jobs_resp_jobs_inner_steps_inner_time_user(
                    seconds = 56, 
                    microseconds = 56, )
            )
        else:
            return V0043StepTime(
        )
        """

    def testV0043StepTime(self):
        """Test V0043StepTime"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
