# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.slurm_v0041_get_shares200_response_meta import SlurmV0041GetShares200ResponseMeta

class TestSlurmV0041GetShares200ResponseMeta(unittest.TestCase):
    """SlurmV0041GetShares200ResponseMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlurmV0041GetShares200ResponseMeta:
        """Test SlurmV0041GetShares200ResponseMeta
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlurmV0041GetShares200ResponseMeta`
        """
        model = SlurmV0041GetShares200ResponseMeta()
        if include_optional:
            return SlurmV0041GetShares200ResponseMeta(
                plugin = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_plugin.slurm_v0041_get_shares_200_response_meta_plugin(
                    type = '', 
                    name = '', 
                    data_parser = '', 
                    accounting_storage = '', ),
                client = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_client.slurm_v0041_get_shares_200_response_meta_client(
                    source = '', 
                    user = '', 
                    group = '', ),
                command = [
                    ''
                    ],
                slurm = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_slurm.slurm_v0041_get_shares_200_response_meta_slurm(
                    version = slurmrestapi.models.slurm_v0041_get_shares_200_response_meta_slurm_version.slurm_v0041_get_shares_200_response_meta_slurm_version(
                        major = '', 
                        micro = '', 
                        minor = '', ), 
                    release = '', 
                    cluster = '', )
            )
        else:
            return SlurmV0041GetShares200ResponseMeta(
        )
        """

    def testSlurmV0041GetShares200ResponseMeta(self):
        """Test SlurmV0041GetShares200ResponseMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
