# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0044_step_step import V0044StepStep

class TestV0044StepStep(unittest.TestCase):
    """V0044StepStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044StepStep:
        """Test V0044StepStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044StepStep`
        """
        model = V0044StepStep()
        if include_optional:
            return V0044StepStep(
                id = '',
                name = '',
                stderr = '',
                stdin = '',
                stdout = '',
                stderr_expanded = '',
                stdin_expanded = '',
                stdout_expanded = ''
            )
        else:
            return V0044StepStep(
        )
        """

    def testV0044StepStep(self):
        """Test V0044StepStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
