# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.3
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0043_coord import V0043Coord

class TestV0043Coord(unittest.TestCase):
    """V0043Coord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0043Coord:
        """Test V0043Coord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0043Coord`
        """
        model = V0043Coord()
        if include_optional:
            return V0043Coord(
                name = '',
                direct = True
            )
        else:
            return V0043Coord(
                name = '',
        )
        """

    def testV0043Coord(self):
        """Test V0043Coord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
