# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0041_openapi_job_info_resp_jobs_inner_deadline import V0041OpenapiJobInfoRespJobsInnerDeadline

class TestV0041OpenapiJobInfoRespJobsInnerDeadline(unittest.TestCase):
    """V0041OpenapiJobInfoRespJobsInnerDeadline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0041OpenapiJobInfoRespJobsInnerDeadline:
        """Test V0041OpenapiJobInfoRespJobsInnerDeadline
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0041OpenapiJobInfoRespJobsInnerDeadline`
        """
        model = V0041OpenapiJobInfoRespJobsInnerDeadline()
        if include_optional:
            return V0041OpenapiJobInfoRespJobsInnerDeadline(
                set = True,
                infinite = True,
                number = 56
            )
        else:
            return V0041OpenapiJobInfoRespJobsInnerDeadline(
        )
        """

    def testV0041OpenapiJobInfoRespJobsInnerDeadline(self):
        """Test V0041OpenapiJobInfoRespJobsInnerDeadline"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
