# coding: utf-8

"""
    Slurm REST API

    API to access and control Slurm

    The version of the OpenAPI document: Slurm-25.11.4
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from slurmrestapi.models.v0044_qos_limits_max_jobs_active_jobs_per import V0044QosLimitsMaxJobsActiveJobsPer

class TestV0044QosLimitsMaxJobsActiveJobsPer(unittest.TestCase):
    """V0044QosLimitsMaxJobsActiveJobsPer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0044QosLimitsMaxJobsActiveJobsPer:
        """Test V0044QosLimitsMaxJobsActiveJobsPer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0044QosLimitsMaxJobsActiveJobsPer`
        """
        model = V0044QosLimitsMaxJobsActiveJobsPer()
        if include_optional:
            return V0044QosLimitsMaxJobsActiveJobsPer(
                account = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, ),
                user = slurmrestapi.models.v0/0/44_uint32_no_val_struct.v0.0.44_uint32_no_val_struct(
                    set = True, 
                    infinite = True, 
                    number = 56, )
            )
        else:
            return V0044QosLimitsMaxJobsActiveJobsPer(
        )
        """

    def testV0044QosLimitsMaxJobsActiveJobsPer(self):
        """Test V0044QosLimitsMaxJobsActiveJobsPer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
