# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import slurmrestapi
from slurmrestapi.model.dbv0038_meta import Dbv0038Meta
from slurmrestapi import configuration


class TestDbv0038Meta(unittest.TestCase):
    """Dbv0038Meta unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
