# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import slurmrestapi
from slurmrestapi.model.v0038_partitions_response import V0038PartitionsResponse
from slurmrestapi import configuration


class TestV0038PartitionsResponse(unittest.TestCase):
    """V0038PartitionsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
