# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import slurmrestapi
from slurmrestapi.model.dbv0037_job_exit_code import Dbv0037JobExitCode
from slurmrestapi import configuration


class TestDbv0037JobExitCode(unittest.TestCase):
    """Dbv0037JobExitCode unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
