# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.39
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import slurmrestapi
from slurmrestapi.model.v0039_job_desc_msg_argv import V0039JobDescMsgArgv
from slurmrestapi import configuration


class TestV0039JobDescMsgArgv(unittest.TestCase):
    """V0039JobDescMsgArgv unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
