# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.39
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import slurmrestapi
from slurmrestapi.model.dbv0039_account_info import Dbv0039AccountInfo
from slurmrestapi import configuration


class TestDbv0039AccountInfo(unittest.TestCase):
    """Dbv0039AccountInfo unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
