# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.39
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import slurmrestapi
from slurmrestapi.model.v0039_step_tres_req_min import V0039StepTresReqMin
from slurmrestapi import configuration


class TestV0039StepTresReqMin(unittest.TestCase):
    """V0039StepTresReqMin unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
