# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.  # noqa: E501

    The version of the OpenAPI document: 0.0.38
    Contact: sales@schedmd.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import slurmrestapi
from slurmrestapi.model.v0038_ping import V0038Ping
from slurmrestapi import configuration


class TestV0038Ping(unittest.TestCase):
    """V0038Ping unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
