# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import slurmrestapi
from slurmrestapi.paths.slurmdb_v0_0_37_cluster_cluster_name import delete  # noqa: E501
from slurmrestapi import configuration, schemas, api_client

from .. import ApiTestMixin


class TestSlurmdbV0037ClusterClusterName(ApiTestMixin, unittest.TestCase):
    """
    SlurmdbV0037ClusterClusterName unit test stubs
        Delete cluster  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = delete.ApiFordelete(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
